server {
    listen 80;

    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location = / {
        proxy_pass http://shared-app:5003;
    }

    location = /home {
        proxy_pass http://shared-app:5003;
    }

    location = /login {
        proxy_pass http://shared-app:5003;
    }

    location = /register {
        proxy_pass http://shared-app:5003;
    }

    location = /welcome {
        proxy_pass http://shared-app:5003;
    }

    location = /logout {
        proxy_pass http://shared-app:5003;
    }

    location /css/ {
        proxy_pass http://shared-app:5003;
    }




    #   -------------------------
    # Student 3 
    # Booking and itinerary features
    #   -------------------------
    location /booking {
        proxy_pass http://student2-frontend:5002;
    }

    location /itinerary {
        proxy_pass http://student2-frontend:5002;
    }

    location /static/ {
    proxy_pass http://student2-frontend:5002;
    }


    #--------------------------
    #student 5
    #--------------------------

    location = /pre-trip {
    proxy_pass http://student5-frontend:8505/;
    }
    
    location /partials/ {
    proxy_pass http://student5-frontend:8505;
    }
    
    location /documents {
    proxy_pass http://student5-frontend:8505;
    }
    
    location /requirements {
    proxy_pass http://student5-frontend:8505;
    }
    
    location /checklist {
    proxy_pass http://student5-frontend:8505;
    }
    
    location /tasks {
    proxy_pass http://student5-frontend:8505;
    }
    
    location /ai/ {
    proxy_pass http://student5-frontend:8505;
    }



    # -------------------------
    # Other student features
    # Add later
    # -------------------------

}
