server {
    listen 80;

    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location = / {
        try_files /home.html =404;
    }

    location = /home {
        try_files /home.html =404;
    }

    location = /login {
        try_files /login.html =404;
    }

    location = /register {
        try_files /register.html =404;
    }

    location = /welcome {
        try_files /welcome.html =404;
    }

    location /css/ {
        try_files $uri =404;
    }




    #   -------------------------
    # Student 3 
    # Booking and itinerary features
    #   -------------------------
    location /booking {
        proxy_pass http://student3-frontend:5002;
    }

    location /itinerary {
        proxy_pass http://student3-frontend:5002;
    }



    # -------------------------
    # Other student features
    # Add later
    # -------------------------

}